name: color_decoder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^1.1.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  toggle_switch: ^2.0.1
  excel: ^2.0.0-null-safety-3
  file_picker: ^5.2.0+1
  path_provider: ^2.0.5
  spreadsheet_decoder: ^2.0.0
  syncfusion_flutter_datagrid_export: ^20.3.47-beta
  open_file: ^3.2.1

dependency_overrides:
  ffi: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

